name: Tools build CI 

on:

  push:
    branches:
      - main

env:
  JENKINS_SERVER_TOKEN: ${{ secrets.JENKINS_SERVER_TOKEN }}
  JENKINS_SERVER_URL: ${{ secrets.JENKINS_SERVER_URL }}
  CERTS_SERVER_NAME: ${{ secrets.CERTS_SERVER_NAME }}

jobs:

  build_linux:      
    if: ${{ github.repository_owner == 'OpenRadioss' }}
    runs-on: ["linux64","prod"]
    container: 
      image: fr-qafactorydev.europe.altair.com/trigger-jenkins
      credentials: 
        username: ${{secrets.DOCKER_REGISTRY_USER}}
        password: ${{secrets.DOCKER_REGISTRY_PASSWD}}
      volumes: 
        - /etc/localtime:/etc/localtime:ro  
        - /etc/docker/certs.d:/etc/docker/certs.d:ro

    env:
      USERLIB_SDK_JOB_NAME: "github_build_userlib_sdk_linux64"
  
    steps:
      - name: Trigger jenkins
        run: |
          # We use ceritificate to connect to jenkins and a crumb (new wayt to do)
          crumb=$(curl -u adminqa:${JENKINS_SERVER_TOKEN} --capath "/etc/docker/certs.d/${CERTS_SERVER_NAME}" --cacert "/etc/docker/certs.d/${CERTS_SERVER_NAME}/wildcard_europe_altair_com.crt" -s "${JENKINS_SERVER_URL}/crumbIssuer/api/json" | grep -oP '"crumb":"\K[^"]+')
          curl -u adminqa:${JENKINS_SERVER_TOKEN} --capath "/etc/docker/certs.d/${CERTS_SERVER_NAME}" --cacert "/etc/docker/certs.d/${CERTS_SERVER_NAME}/wildcard_europe_altair_com.crt" -H "Jenkins-Crumb:$crumb" -X POST "${JENKINS_SERVER_URL}/job/${USERLIB_SDK_JOB_NAME}/buildWithParameters?commit_id=${GITHUB_SHA}"

